In [51]:
import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors
import matplotlib.pyplot as plt
import seaborn as sns


In [52]:
r_cols = ['user_id', 'item_id', 'rating']

dataset = pd.read_csv('./ratings.csv', sep=',', names=r_cols, encoding='latin-1', header=0)
dataset .head()

user_id  item_id  rating
0        1        1     5.0
1        1      778     5.0
2        1     1365     5.0
3        1     1559     5.0
4        1      778     5.0

In [53]:
n_users = dataset.user_id.unique().shape[0]
n_items = dataset.item_id.unique().shape[0]
n_items = dataset['item_id'].max()
A = np.zeros((n_users,n_items))
for line in dataset.itertuples():
    A[line[1]-1,line[2]-1] = line[3]
print("Original rating matrix : ",A)


Original rating matrix :  [[5. 0. 0. ... 0. 0. 0.]
 [0. 5. 0. ... 0. 0. 0.]
 [0. 0. 5. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [54]:
for i in range(len(A)):
  for j in range(len(A[0])):
    if A[i][j]>=3:
      A[i][j]=1
    else:
      A[i][j]=0

In [55]:
csr_sample = csr_matrix(A)
print(csr_sample)

  (0, 0)	1.0
  (0, 48)	1.0
  (0, 51)	1.0
  (0, 92)	1.0
  (0, 192)	1.0
  (0, 216)	1.0
  (0, 279)	1.0
  (0, 313)	1.0
  (0, 326)	1.0
  (0, 336)	1.0
  (0, 401)	1.0
  (0, 409)	1.0
  (0, 437)	1.0
  (0, 486)	1.0
  (0, 515)	1.0
  (0, 575)	1.0
  (0, 583)	1.0
  (0, 597)	1.0
  (0, 604)	1.0
  (0, 629)	1.0
  (0, 694)	1.0
  (0, 710)	1.0
  (0, 777)	1.0
  (0, 873)	1.0
  (0, 945)	1.0
  :	:
  (1306, 9046)	1.0
  (1306, 10538)	1.0
  (1306, 12228)	1.0
  (1306, 13193)	1.0
  (1306, 13194)	1.0
  (1306, 13195)	1.0
  (1306, 13198)	1.0
  (1306, 13203)	1.0
  (1307, 291)	1.0
  (1307, 1028)	1.0
  (1307, 1569)	1.0
  (1307, 3357)	1.0
  (1307, 3477)	1.0
  (1307, 3513)	1.0
  (1307, 4615)	1.0
  (1307, 5711)	1.0
  (1307, 5764)	1.0
  (1307, 5972)	1.0
  (1307, 6572)	1.0
  (1307, 7226)	1.0
  (1307, 8406)	1.0
  (1307, 11964)	1.0
  (1307, 13493)	1.0
  (1307, 13500)	1.0
  (1307, 13501)	1.0


In [56]:
knn = NearestNeighbors(metric='cosine', algorithm='brute', n_neighbors=3, n_jobs=-1)
knn.fit(csr_sample)

NearestNeighbors(algorithm='brute', metric='cosine', n_jobs=-1, n_neighbors=3)

In [61]:
dataset_sort_des = dataset.sort_values(['user_id', 'rating'], ascending=[True, False])
filter1 = dataset_sort_des[dataset_sort_des['user_id'] == 1].item_id
filter1 = filter1.tolist()
filter1 = filter1[:20]

print("Items liked by user: ",filter1)

Items liked by user:  [1, 778, 1365, 1559, 778, 1365, 1559, 778, 1365, 1559, 778, 1365, 1559, 49, 49, 2402, 5871, 3725, 2431, 5936]


In [59]:
distances1=[]
indices1=[]
for i in filter1:
  distances , indices = knn.kneighbors(csr_sample[i],n_neighbors=3)
  indices = indices.flatten()
  indices= indices[1:]
  indices1.extend(indices)
print("Items to be recommended: ",indices1)

IndexError: row index (1365) out of range

In [49]:
print("CSR matrix shape:", csr_sample.shape)
print("Max item_id in dataset:", dataset['item_id'].max())


CSR matrix shape: (1308, 13988)
Max item_id in dataset: 13988
